version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@1.4.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@1.0.2
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - checkout
      - circleci/aws-elastic-beanstalk@1.0.2
      - run:
          name: Back-End Install
          command: npm run backend:install
      - run:
          name: Back-End Build
          command: npm run backend:build
      - run:
          name: Deploy App
          command: npm run backend:deploy
