version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@1.4.0
  eb: circleci/aws-elastic-beanstalk@1.0.0

#Need the workflow so it only deploys from main
workflows:
  version: 1
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main

jobs:
  deploy:
    docker:
      - image: "cimg/base:stable"
    # All scripts are in package.json so the CI/CD does not care about the environment
    steps:
      - node/install
      - checkout
      - aws-cli/setup 
      - checkout
      - eb/setup
      - run:
          name: Back-End Install
          command: npm run backend:install
      - run:
          name: Back-End Build
          command: npm run backend:build
      - run:
          name: Deploy App
          command: npm run backend:deploy
      - run:
          name: Deploy ENV Variables to EB
          command: eb setenv POSTGRES_USERNAME=$POSTGRES_USERNAME |
            eb setenv POSTGRES_PASSWORD=$POSTGRES_PASSWORD |
            eb setenv POSTGRES_DB=$POSTGRES_DB |
            eb setenv POSTGRES_HOST=$POSTGRES_HOST |
            eb setenv PORT=$PORT |
            eb setenv AWS_REGION=$AWS_REGION |
            eb setenv AWS_PROFILE=$AWS_PROFILE |
            eb setenv AWS_BUCKET=$AWS_BUCKET |
            eb setenv AWS_ACCESS_KEY=$AWS_ACCESS_KEY |
            eb setenv AWS_SECRET=$AWS_SECRET |
            eb setenv JWT_SECRET=$JWT_SECRET
