version: 2.1
orbs:
  node: circleci/node@4.2.0
  aws-cli: circleci/aws-cli@1.4.0
  eb: circleci/aws-elastic-beanstalk@1.0.0
#Need the worklfow so it only deploys from main
workflows:
  version: 1
  build-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - main
jobs:
  deploy:
    docker:
      - image: "cimg/base:stable"
    # All scripts are in package.json so the CI/CD does not care about the environment
    steps:
      - node/install
      - checkout
      - aws-cli/setup #Installing AWS to be able to Copy to S3
      - checkout
      - eb/setup #Installing Elastic-Beanstalk to be able to deploy to EB
      - run:
          name: Back-End Install
          command: npm run backend:install
      - run:
          name: Back-End Build
          command: npm run backend:build
      - run:
          name: Deploy App
          command: npm run backend:deploy
